const ciudades = [];

ciudades.push({ code: 1, name: 'Medellin - Antioquia' });
ciudades.push({ code: 2, name: 'Abejorral - Antioquia' });
ciudades.push({ code: 3, name: 'Abriaquí - Antioquia' });
ciudades.push({ code: 4, name: 'Alejandría - Antioquia' });
ciudades.push({ code: 5, name: 'Amagá - Antioquia' });
ciudades.push({ code: 6, name: 'Amalfi - Antioquia' });
ciudades.push({ code: 7, name: 'Andes - Antioquia' });
ciudades.push({ code: 8, name: 'Angelópolis - Antioquia' });
ciudades.push({ code: 9, name: 'Angostura - Antioquia' });
ciudades.push({ code: 10, name: 'Anorí - Antioquia' });
ciudades.push({ code: 11, name: 'Anza - Antioquia' });
ciudades.push({ code: 12, name: 'Apartadó - Antioquia' });
ciudades.push({ code: 13, name: 'Arboletes - Antioquia' });
ciudades.push({ code: 14, name: 'Argelia - Antioquia' });
ciudades.push({ code: 15, name: 'Armenia - Antioquia' });
ciudades.push({ code: 16, name: 'Barbosa - Antioquia' });
ciudades.push({ code: 17, name: 'Bello - Antioquia' });
ciudades.push({ code: 18, name: 'Betania - Antioquia' });
ciudades.push({ code: 19, name: 'Betulia - Antioquia' });
ciudades.push({ code: 20, name: 'Ciudad Bolívar - Antioquia' });
ciudades.push({ code: 21, name: 'Briceño - Antioquia' });
ciudades.push({ code: 22, name: 'Buriticá - Antioquia' });
ciudades.push({ code: 23, name: 'Cáceres - Antioquia' });
ciudades.push({ code: 24, name: 'Caicedo - Antioquia' });
ciudades.push({ code: 25, name: 'Caldas - Antioquia' });
ciudades.push({ code: 26, name: 'Campamento - Antioquia' });
ciudades.push({ code: 27, name: 'Cañasgordas - Antioquia' });
ciudades.push({ code: 28, name: 'Caracolí - Antioquia' });
ciudades.push({ code: 29, name: 'Caramanta - Antioquia' });
ciudades.push({ code: 30, name: 'Carepa - Antioquia' });
ciudades.push({ code: 31, name: 'Carolina - Antioquia' });
ciudades.push({ code: 32, name: 'Caucasia - Antioquia' });
ciudades.push({ code: 33, name: 'Chigorodó - Antioquia' });
ciudades.push({ code: 34, name: 'Cisneros - Antioquia' });
ciudades.push({ code: 35, name: 'Cocorná - Antioquia' });
ciudades.push({ code: 36, name: 'Concepción - Antioquia' });
ciudades.push({ code: 37, name: 'Concordia - Antioquia' });
ciudades.push({ code: 38, name: 'Copacabana - Antioquia' });
ciudades.push({ code: 39, name: 'Dabeiba - Antioquia' });
ciudades.push({ code: 40, name: 'Don Matías - Antioquia' });
ciudades.push({ code: 41, name: 'Ebéjico - Antioquia' });
ciudades.push({ code: 42, name: 'El Bagre - Antioquia' });
ciudades.push({ code: 43, name: 'Entrerrios - Antioquia' });
ciudades.push({ code: 44, name: 'Envigado - Antioquia' });
ciudades.push({ code: 45, name: 'Fredonia - Antioquia' });
ciudades.push({ code: 46, name: 'Giraldo - Antioquia' });
ciudades.push({ code: 47, name: 'Girardota - Antioquia' });
ciudades.push({ code: 48, name: 'Gómez Plata - Antioquia' });
ciudades.push({ code: 49, name: 'Guadalupe - Antioquia' });
ciudades.push({ code: 50, name: 'Guarne - Antioquia' });
ciudades.push({ code: 51, name: 'Guatapé - Antioquia' });
ciudades.push({ code: 52, name: 'Heliconia - Antioquia' });
ciudades.push({ code: 53, name: 'Hispania - Antioquia' });
ciudades.push({ code: 54, name: 'Itagui - Antioquia' });
ciudades.push({ code: 55, name: 'Ituango - Antioquia' });
ciudades.push({ code: 56, name: 'Jericó - Antioquia' });
ciudades.push({ code: 57, name: 'La Ceja - Antioquia' });
ciudades.push({ code: 58, name: 'La Estrella - Antioquia' });
ciudades.push({ code: 59, name: 'La Pintada - Antioquia' });
ciudades.push({ code: 60, name: 'La Unión - Antioquia' });
ciudades.push({ code: 61, name: 'Liborina - Antioquia' });
ciudades.push({ code: 62, name: 'Maceo - Antioquia' });
ciudades.push({ code: 63, name: 'Marinilla - Antioquia' });
ciudades.push({ code: 64, name: 'Montebello - Antioquia' });
ciudades.push({ code: 65, name: 'Murindó - Antioquia' });
ciudades.push({ code: 66, name: 'Barranquilla - Atlantico' });
ciudades.push({ code: 67, name: 'Baranoa - Atlantico' });
ciudades.push({ code: 68, name: 'Candelaria - Atlantico' });
ciudades.push({ code: 69, name: 'Galapa - Atlantico' });
ciudades.push({ code: 70, name: 'Luruaco - Atlantico' });
ciudades.push({ code: 71, name: 'Malambo - Atlantico' });
ciudades.push({ code: 72, name: 'Manatí - Atlantico' });
ciudades.push({ code: 73, name: 'Piojo - Atlantico' });
ciudades.push({ code: 74, name: 'Polonuevo - Atlantico' });
ciudades.push({ code: 75, name: 'Sabanagrande - Atlantico' });
ciudades.push({ code: 76, name: 'Sabanalarga - Atlantico' });
ciudades.push({ code: 77, name: 'Santa Lucía - Atlantico' });
ciudades.push({ code: 78, name: 'Santo Tomas - Atlantico' });
ciudades.push({ code: 79, name: 'Soledad - Atlantico' });
ciudades.push({ code: 80, name: 'Suan - Atlantico' });
ciudades.push({ code: 81, name: 'Tubara - Atlantico' });
ciudades.push({ code: 82, name: 'Usiacurí - Atlantico' });
ciudades.push({ code: 83, name: 'Achí - Bolivar' });
ciudades.push({ code: 84, name: 'Arenal - Bolivar' });
ciudades.push({ code: 85, name: 'Arjona - Bolivar' });
ciudades.push({ code: 86, name: 'Arroyohondo - Bolivar' });
ciudades.push({ code: 87, name: 'Calamar - Bolivar' });
ciudades.push({ code: 88, name: 'Cantagallo - Bolivar' });
ciudades.push({ code: 89, name: 'Cicuco - Bolivar' });
ciudades.push({ code: 90, name: 'Córdoba - Bolivar' });
ciudades.push({ code: 91, name: 'Clemencia - Bolivar' });
ciudades.push({ code: 92, name: 'El Guamo - Bolivar' });
ciudades.push({ code: 93, name: 'Magangué - Bolivar' });
ciudades.push({ code: 94, name: 'Mahates - Bolivar' });
ciudades.push({ code: 95, name: 'Margarita - Bolivar' });
ciudades.push({ code: 96, name: 'Montecristo - Bolivar' });
ciudades.push({ code: 97, name: 'Mompós - Bolivar' });
ciudades.push({ code: 98, name: 'Morales - Bolivar' });
ciudades.push({ code: 99, name: 'Norosí - Bolivar' });
ciudades.push({ code: 100, name: 'Pinillos - Bolivar' });
ciudades.push({ code: 101, name: 'Regidor - Bolivar' });
ciudades.push({ code: 102, name: 'Río Viejo - Bolivar' });
ciudades.push({ code: 103, name: 'San Estanislao - Bolivar' });
ciudades.push({ code: 104, name: 'San Fernando - Bolivar' });
ciudades.push({ code: 105, name: 'San Juan Nepomuceno - Bolivar' });
ciudades.push({ code: 106, name: 'Santa Catalina - Bolivar' });
ciudades.push({ code: 107, name: 'Santa Rosa - Bolivar' });
ciudades.push({ code: 108, name: 'Simití - Bolivar' });
ciudades.push({ code: 109, name: 'Soplaviento - Bolivar' });
ciudades.push({ code: 110, name: 'Talaigua Nuevo - Bolivar' });
ciudades.push({ code: 111, name: 'Tiquisio - Bolivar' });
ciudades.push({ code: 112, name: 'Turbaco - Bolivar' });
ciudades.push({ code: 113, name: 'Turbaná - Bolivar' });
ciudades.push({ code: 114, name: 'Villanueva - Bolivar' });
ciudades.push({ code: 115, name: 'Tunja - Boyaca' });
ciudades.push({ code: 116, name: 'Almeida - Boyaca' });
ciudades.push({ code: 117, name: 'Aquitania - Boyaca' });
ciudades.push({ code: 118, name: 'Arcabuco - Boyaca' });
ciudades.push({ code: 119, name: 'Berbeo - Boyaca' });
ciudades.push({ code: 120, name: 'Betéitiva - Boyaca' });
ciudades.push({ code: 121, name: 'Boavita - Boyaca' });
ciudades.push({ code: 122, name: 'Boyacá - Boyaca' });
ciudades.push({ code: 123, name: 'Briceño - Boyaca' });
ciudades.push({ code: 124, name: 'Buena Vista - Boyaca' });
ciudades.push({ code: 125, name: 'Busbanzá - Boyaca' });
ciudades.push({ code: 126, name: 'Caldas - Boyaca' });
ciudades.push({ code: 127, name: 'Campohermoso - Boyaca' });
ciudades.push({ code: 128, name: 'Cerinza - Boyaca' });
ciudades.push({ code: 129, name: 'Chinavita - Boyaca' });
ciudades.push({ code: 130, name: 'Chiquinquirá - Boyaca' });
ciudades.push({ code: 131, name: 'Chiscas - Boyaca' });
ciudades.push({ code: 132, name: 'Chita - Boyaca' });
ciudades.push({ code: 133, name: 'Chitaraque - Boyaca' });
ciudades.push({ code: 134, name: 'Chivatá - Boyaca' });
ciudades.push({ code: 135, name: 'Cómbita - Boyaca' });
ciudades.push({ code: 136, name: 'Coper - Boyaca' });
ciudades.push({ code: 137, name: 'Corrales - Boyaca' });
ciudades.push({ code: 138, name: 'Covarachía - Boyaca' });
ciudades.push({ code: 139, name: 'Cubará - Boyaca' });
ciudades.push({ code: 140, name: 'Cucaita - Boyaca' });
ciudades.push({ code: 141, name: 'Cuítiva - Boyaca' });
ciudades.push({ code: 142, name: 'Chíquiza - Boyaca' });
ciudades.push({ code: 143, name: 'Chivor - Boyaca' });
ciudades.push({ code: 144, name: 'Duitama - Boyaca' });
ciudades.push({ code: 145, name: 'El Cocuy - Boyaca' });
ciudades.push({ code: 146, name: 'El Espino - Boyaca' });
ciudades.push({ code: 147, name: 'Firavitoba - Boyaca' });
ciudades.push({ code: 148, name: 'Floresta - Boyaca' });
ciudades.push({ code: 149, name: 'Gachantivá - Boyaca' });
ciudades.push({ code: 150, name: 'Gameza - Boyaca' });
ciudades.push({ code: 151, name: 'Garagoa - Boyaca' });
ciudades.push({ code: 152, name: 'Guacamayas - Boyaca' });
ciudades.push({ code: 153, name: 'Guateque - Boyaca' });
ciudades.push({ code: 154, name: 'Guayatá - Boyaca' });
ciudades.push({ code: 155, name: 'Güicán - Boyaca' });
ciudades.push({ code: 156, name: 'Iza - Boyaca' });
ciudades.push({ code: 157, name: 'Jenesano - Boyaca' });
ciudades.push({ code: 158, name: 'Jericó - Boyaca' });
ciudades.push({ code: 159, name: 'Labranzagrande - Boyaca' });
ciudades.push({ code: 160, name: 'La Capilla - Boyaca' });
ciudades.push({ code: 161, name: 'La Victoria - Boyaca' });
ciudades.push({ code: 162, name: 'Macanal - Boyaca' });
ciudades.push({ code: 163, name: 'Manizales - Caqueta' });
ciudades.push({ code: 164, name: 'Aguadas - Caqueta' });
ciudades.push({ code: 165, name: 'Anserma - Caqueta' });
ciudades.push({ code: 166, name: 'Aranzazu - Caqueta' });
ciudades.push({ code: 167, name: 'Belalcázar - Caqueta' });
ciudades.push({ code: 168, name: 'Chinchiná - Caqueta' });
ciudades.push({ code: 169, name: 'Filadelfia - Caqueta' });
ciudades.push({ code: 170, name: 'La Dorada - Caqueta' });
ciudades.push({ code: 171, name: 'La Merced - Caqueta' });
ciudades.push({ code: 172, name: 'Manzanares - Caqueta' });
ciudades.push({ code: 173, name: 'Marmato - Caqueta' });
ciudades.push({ code: 174, name: 'Marulanda - Caqueta' });
ciudades.push({ code: 175, name: 'Neira - Caqueta' });
ciudades.push({ code: 176, name: 'Norcasia - Caqueta' });
ciudades.push({ code: 177, name: 'Pácora - Caqueta' });
ciudades.push({ code: 178, name: 'Palestina - Caqueta' });
ciudades.push({ code: 179, name: 'Pensilvania - Caqueta' });
ciudades.push({ code: 180, name: 'Riosucio - Caqueta' });
ciudades.push({ code: 181, name: 'Risaralda - Caqueta' });
ciudades.push({ code: 182, name: 'Salamina  - Caqueta' });
ciudades.push({ code: 183, name: 'Samaná - Caqueta' });
ciudades.push({ code: 184, name: 'San José - Caqueta' });
ciudades.push({ code: 185, name: 'Supía - Caqueta' });
ciudades.push({ code: 186, name: 'Victoria - Caqueta' });
ciudades.push({ code: 187, name: 'Villamaría - Caqueta' });
ciudades.push({ code: 188, name: 'Viterbo - Caqueta' });
ciudades.push({ code: 189, name: 'Florencia - Caqueta' });
ciudades.push({ code: 190, name: 'Albania - Caqueta' });
ciudades.push({ code: 191, name: 'Curillo - Caqueta' });
ciudades.push({ code: 192, name: 'El Doncello - Caqueta' });
ciudades.push({ code: 193, name: 'El Paujil - Caqueta' });
ciudades.push({ code: 194, name: 'Morelia - Caqueta' });
ciudades.push({ code: 195, name: 'Puerto Rico - Caqueta' });
ciudades.push({ code: 196, name: 'Solano - Caqueta' });
ciudades.push({ code: 197, name: 'Solita  - Caqueta' });
ciudades.push({ code: 198, name: 'Valparaíso - Caqueta' });
ciudades.push({ code: 199, name: 'Popayán - Cauca' });
ciudades.push({ code: 200, name: 'Almaguer - Cauca' });
ciudades.push({ code: 201, name: 'Argelia - Cauca' });
ciudades.push({ code: 202, name: 'Balboa - Cauca' });
ciudades.push({ code: 203, name: 'Bolívar - Cauca' });
ciudades.push({ code: 204, name: 'Buenos Aires - Cauca' });
ciudades.push({ code: 205, name: 'Cajibío - Cauca' });
ciudades.push({ code: 206, name: 'Caldono - Cauca' });
ciudades.push({ code: 207, name: 'Caloto - Cauca' });
ciudades.push({ code: 208, name: 'Corinto - Cauca' });
ciudades.push({ code: 209, name: 'El Tambo - Cauca' });
ciudades.push({ code: 210, name: 'Florencia - Cauca' });
ciudades.push({ code: 211, name: 'Guachené - Cauca' });
ciudades.push({ code: 212, name: 'Guapi - Cauca' });
ciudades.push({ code: 213, name: 'Inzá - Cauca' });
ciudades.push({ code: 214, name: 'Jambaló - Cauca' });
ciudades.push({ code: 215, name: 'La Sierra - Cauca' });
ciudades.push({ code: 216, name: 'La Vega - Cauca' });
ciudades.push({ code: 217, name: 'López - Cauca' });
ciudades.push({ code: 218, name: 'Mercaderes - Cauca' });
ciudades.push({ code: 219, name: 'Miranda - Cauca' });
ciudades.push({ code: 220, name: 'Morales - Cauca' });
ciudades.push({ code: 221, name: 'Padilla - Cauca' });
ciudades.push({ code: 222, name: 'Patía - Cauca' });
ciudades.push({ code: 223, name: 'Piamonte - Cauca' });
ciudades.push({ code: 224, name: 'Piendamó - Cauca' });
ciudades.push({ code: 225, name: 'Puerto Tejada - Cauca' });
ciudades.push({ code: 226, name: 'Puracé - Cauca' });
ciudades.push({ code: 227, name: 'Rosas - Cauca' });
ciudades.push({ code: 228, name: 'Santa Rosa - Cauca' });
ciudades.push({ code: 229, name: 'Silvia - Cauca' });
ciudades.push({ code: 230, name: 'Sotara - Cauca' });
ciudades.push({ code: 231, name: 'Suárez - Cauca' });
ciudades.push({ code: 232, name: 'Sucre - Cauca' });
ciudades.push({ code: 233, name: 'Timbío - Cauca' });
ciudades.push({ code: 234, name: 'Timbiquí - Cauca' });
ciudades.push({ code: 235, name: 'Toribio - Cauca' });
ciudades.push({ code: 236, name: 'Totoró - Cauca' });
ciudades.push({ code: 237, name: 'Villa Rica - Cauca' });
ciudades.push({ code: 238, name: 'Valledupar - Cesar' });
ciudades.push({ code: 239, name: 'Aguachicar - Cesar' });
ciudades.push({ code: 240, name: 'Agustín Codazzir - Cesar' });
ciudades.push({ code: 241, name: 'Astrear - Cesar' });
ciudades.push({ code: 242, name: 'Becerrilr - Cesar' });
ciudades.push({ code: 243, name: 'Bosconiar - Cesar' });
ciudades.push({ code: 244, name: 'Chimichaguar - Cesar' });
ciudades.push({ code: 245, name: 'Chiriguanár - Cesar' });
ciudades.push({ code: 246, name: 'Curumanír - Cesar' });
ciudades.push({ code: 247, name: 'El Copeyr - Cesar' });
ciudades.push({ code: 248, name: 'El Pasor - Cesar' });
ciudades.push({ code: 249, name: 'Gamarrar - Cesar' });
ciudades.push({ code: 250, name: 'Gonzálezr - Cesar' });
ciudades.push({ code: 251, name: 'La Gloriar - Cesar' });
ciudades.push({ code: 252, name: 'Manaurer - Cesar' });
ciudades.push({ code: 253, name: 'Pailitasr - Cesar' });
ciudades.push({ code: 254, name: 'Pelayar - Cesar' });
ciudades.push({ code: 255, name: 'Pueblo Bellor - Cesar' });
ciudades.push({ code: 256, name: 'La Pazr - Cesar' });
ciudades.push({ code: 257, name: 'San Albertor - Cesar' });
ciudades.push({ code: 258, name: 'San Diegor - Cesar' });
ciudades.push({ code: 259, name: 'San Martínr - Cesar' });
ciudades.push({ code: 260, name: 'Tamalamequer - Cesar' });
ciudades.push({ code: 261, name: 'Montería - Cordoba' });
ciudades.push({ code: 262, name: 'Ayapel - Cordoba' });
ciudades.push({ code: 263, name: 'Buenavista - Cordoba' });
ciudades.push({ code: 264, name: 'Canalete - Cordoba' });
ciudades.push({ code: 265, name: 'Cereté - Cordoba' });
ciudades.push({ code: 266, name: 'Chimá - Cordoba' });
ciudades.push({ code: 267, name: 'Chinú - Cordoba' });
ciudades.push({ code: 268, name: 'Cotorra - Cordoba' });
ciudades.push({ code: 269, name: 'Lorica - Cordoba' });
ciudades.push({ code: 270, name: 'Los Córdobas - Cordoba' });
ciudades.push({ code: 271, name: 'Momil - Cordoba' });
ciudades.push({ code: 272, name: 'Moñitos - Cordoba' });
ciudades.push({ code: 273, name: 'Planeta Rica - Cordoba' });
ciudades.push({ code: 274, name: 'Pueblo Nuevo - Cordoba' });
ciudades.push({ code: 275, name: 'Puerto Escondido - Cordoba' });
ciudades.push({ code: 276, name: 'Purísima - Cordoba' });
ciudades.push({ code: 277, name: 'Sahagún - Cordoba' });
ciudades.push({ code: 278, name: 'San Andrés Sotavento - Cordoba' });
ciudades.push({ code: 279, name: 'San Antero - Cordoba' });
ciudades.push({ code: 280, name: 'San Pelayo - Cordoba' });
ciudades.push({ code: 281, name: 'Tierralta - Cordoba' });
ciudades.push({ code: 282, name: 'Tuchín - Cordoba' });
ciudades.push({ code: 283, name: 'Valencia - Cordoba' });
ciudades.push({ code: 284, name: 'Anapoima - Cundinamarca' });
ciudades.push({ code: 285, name: 'Arbeláez - Cundinamarca' });
ciudades.push({ code: 286, name: 'Beltrán - Cundinamarca' });
ciudades.push({ code: 287, name: 'Bituima - Cundinamarca' });
ciudades.push({ code: 288, name: 'Bojacá - Cundinamarca' });
ciudades.push({ code: 289, name: 'Cabrera - Cundinamarca' });
ciudades.push({ code: 290, name: 'Cachipay - Cundinamarca' });
ciudades.push({ code: 291, name: 'Cajicá - Cundinamarca' });
ciudades.push({ code: 292, name: 'Caparrapí - Cundinamarca' });
ciudades.push({ code: 293, name: 'Caqueza - Cundinamarca' });
ciudades.push({ code: 294, name: 'Chaguaní - Cundinamarca' });
ciudades.push({ code: 295, name: 'Chipaque - Cundinamarca' });
ciudades.push({ code: 296, name: 'Choachí - Cundinamarca' });
ciudades.push({ code: 297, name: 'Chocontá - Cundinamarca' });
ciudades.push({ code: 298, name: 'Cogua - Cundinamarca' });
ciudades.push({ code: 299, name: 'Cota - Cundinamarca' });
ciudades.push({ code: 300, name: 'Cucunubá - Cundinamarca' });
ciudades.push({ code: 301, name: 'El Colegio - Cundinamarca' });
ciudades.push({ code: 302, name: 'El Rosal - Cundinamarca' });
ciudades.push({ code: 303, name: 'Fomeque - Cundinamarca' });
ciudades.push({ code: 304, name: 'Fosca - Cundinamarca' });
ciudades.push({ code: 305, name: 'Funza - Cundinamarca' });
ciudades.push({ code: 306, name: 'Fúquene - Cundinamarca' });
ciudades.push({ code: 307, name: 'Gachala - Cundinamarca' });
ciudades.push({ code: 308, name: 'Gachancipá  - Cundinamarca' });
ciudades.push({ code: 309, name: 'Gachetá - Cundinamarca' });
ciudades.push({ code: 310, name: 'Girardot - Cundinamarca' });
ciudades.push({ code: 311, name: 'Granada - Cundinamarca' });
ciudades.push({ code: 312, name: 'Guachetá - Cundinamarca' });
ciudades.push({ code: 313, name: 'Guaduas - Cundinamarca' });
ciudades.push({ code: 314, name: 'Guasca - Cundinamarca' });
ciudades.push({ code: 315, name: 'Guataquí - Cundinamarca' });
ciudades.push({ code: 316, name: 'Guatavita - Cundinamarca' });
ciudades.push({ code: 317, name: 'Guayabetal - Cundinamarca' });
ciudades.push({ code: 318, name: 'Gutiérrez - Cundinamarca' });
ciudades.push({ code: 319, name: 'Jerusalén - Cundinamarca' });
ciudades.push({ code: 320, name: 'Junín - Cundinamarca' });
ciudades.push({ code: 321, name: 'La Calera - Cundinamarca' });
ciudades.push({ code: 322, name: 'La Mesa - Cundinamarca' });
ciudades.push({ code: 323, name: 'La Palma - Cundinamarca' });
ciudades.push({ code: 324, name: 'Vianí - Cundinamarca' });
ciudades.push({ code: 325, name: 'Villagómez - Cundinamarca' });
ciudades.push({ code: 326, name: 'Villapinzón - Cundinamarca' });
ciudades.push({ code: 327, name: 'Villeta - Cundinamarca' });
ciudades.push({ code: 328, name: 'Viotá - Cundinamarca' });
ciudades.push({ code: 329, name: 'Zipacón - Cundinamarca' });
ciudades.push({ code: 330, name: 'Quibdó - Choco' });
ciudades.push({ code: 331, name: 'Acandí - Choco' });
ciudades.push({ code: 332, name: 'Alto Baudo - Choco' });
ciudades.push({ code: 333, name: 'Atrato - Choco' });
ciudades.push({ code: 334, name: 'Bagadó - Choco' });
ciudades.push({ code: 335, name: 'Bahía Solano - Choco' });
ciudades.push({ code: 336, name: 'Bajo Baudó - Choco' });
ciudades.push({ code: 337, name: 'Bojaya - Choco' });
ciudades.push({ code: 338, name: 'Cértegui - Choco' });
ciudades.push({ code: 339, name: 'Condoto - Choco' });
ciudades.push({ code: 340, name: 'Juradó - Choco' });
ciudades.push({ code: 341, name: 'Lloró - Choco' });
ciudades.push({ code: 342, name: 'Medio Atrato - Choco' });
ciudades.push({ code: 343, name: 'Medio Baudó - Choco' });
ciudades.push({ code: 344, name: 'Medio San Juan - Choco' });
ciudades.push({ code: 345, name: 'Nóvita - Choco' });
ciudades.push({ code: 346, name: 'Nuquí - Choco' });
ciudades.push({ code: 347, name: 'Río Iro - Choco' });
ciudades.push({ code: 348, name: 'Río Quito - Choco' });
ciudades.push({ code: 349, name: 'Riosucio - Choco' });
ciudades.push({ code: 350, name: 'Sipí - Choco' });
ciudades.push({ code: 351, name: 'Unguía - Choco' });
ciudades.push({ code: 352, name: 'Neiva - Huila' });
ciudades.push({ code: 353, name: 'Acevedo - Huila' });
ciudades.push({ code: 354, name: 'Agrado - Huila' });
ciudades.push({ code: 355, name: 'Aipe - Huila' });
ciudades.push({ code: 356, name: 'Algeciras - Huila' });
ciudades.push({ code: 357, name: 'Altamira - Huila' });
ciudades.push({ code: 358, name: 'Baraya - Huila' });
ciudades.push({ code: 359, name: 'Campoalegre - Huila' });
ciudades.push({ code: 360, name: 'Colombia - Huila' });
ciudades.push({ code: 361, name: 'Elías - Huila' });
ciudades.push({ code: 362, name: 'Garzón - Huila' });
ciudades.push({ code: 363, name: 'Gigante - Huila' });
ciudades.push({ code: 364, name: 'Guadalupe - Huila' });
ciudades.push({ code: 365, name: 'Hobo - Huila' });
ciudades.push({ code: 366, name: 'Iquira - Huila' });
ciudades.push({ code: 367, name: 'Isnos - Huila' });
ciudades.push({ code: 368, name: 'La Argentina - Huila' });
ciudades.push({ code: 369, name: 'La Plata - Huila' });
ciudades.push({ code: 370, name: 'Nátaga - Huila' });
ciudades.push({ code: 371, name: 'Oporapa - Huila' });
ciudades.push({ code: 372, name: 'Paicol - Huila' });
ciudades.push({ code: 373, name: 'Palermo - Huila' });
ciudades.push({ code: 374, name: 'Palestina - Huila' });
ciudades.push({ code: 375, name: 'Pital - Huila' });
ciudades.push({ code: 376, name: 'Pitalito - Huila' });
ciudades.push({ code: 377, name: 'Rivera - Huila' });
ciudades.push({ code: 378, name: 'Saladoblanco - Huila' });
ciudades.push({ code: 379, name: 'Santa María - Huila' });
ciudades.push({ code: 380, name: 'Suaza - Huila' });
ciudades.push({ code: 381, name: 'Tarqui - Huila' });
ciudades.push({ code: 382, name: 'Tesalia - Huila' });
ciudades.push({ code: 383, name: 'Tello - Huila' });
ciudades.push({ code: 384, name: 'Teruel - Huila' });
ciudades.push({ code: 385, name: 'Timaná - Huila' });
ciudades.push({ code: 386, name: 'Villavieja - Huila' });
ciudades.push({ code: 387, name: 'Yaguará - Huila' });
ciudades.push({ code: 388, name: 'Riohacha - La Guajira' });
ciudades.push({ code: 389, name: 'Albania - La Guajira' });
ciudades.push({ code: 390, name: 'Barrancas - La Guajira' });
ciudades.push({ code: 391, name: 'Dibula - La Guajira' });
ciudades.push({ code: 392, name: 'Distracción - La Guajira' });
ciudades.push({ code: 393, name: 'El Molino - La Guajira' });
ciudades.push({ code: 394, name: 'Fonseca - La Guajira' });
ciudades.push({ code: 395, name: 'Hatonuevo - La Guajira' });
ciudades.push({ code: 396, name: 'Maicao - La Guajira' });
ciudades.push({ code: 397, name: 'Manaure - La Guajira' });
ciudades.push({ code: 398, name: 'Uribia - La Guajira' });
ciudades.push({ code: 399, name: 'Urumita - La Guajira' });
ciudades.push({ code: 400, name: 'Villanueva - La Guajira' });
ciudades.push({ code: 401, name: 'Santa Marta - Magdalena' });
ciudades.push({ code: 402, name: 'Algarrobo - Magdalena' });
ciudades.push({ code: 403, name: 'Aracataca - Magdalena' });
ciudades.push({ code: 404, name: 'Ariguaní - Magdalena' });
ciudades.push({ code: 405, name: 'Cerro San Antonio - Magdalena' });
ciudades.push({ code: 406, name: 'Chivolo - Magdalena' });
ciudades.push({ code: 407, name: 'Concordia - Magdalena' });
ciudades.push({ code: 408, name: 'El Banco - Magdalena' });
ciudades.push({ code: 409, name: 'El Piñon - Magdalena' });
ciudades.push({ code: 410, name: 'El Retén - Magdalena' });
ciudades.push({ code: 411, name: 'Fundación - Magdalena' });
ciudades.push({ code: 412, name: 'Guamal - Magdalena' });
ciudades.push({ code: 413, name: 'Nueva Granada - Magdalena' });
ciudades.push({ code: 414, name: 'Pedraza - Magdalena' });
ciudades.push({ code: 415, name: 'Pivijay - Magdalena' });
ciudades.push({ code: 416, name: 'Plato - Magdalena' });
ciudades.push({ code: 417, name: 'Remolino - Magdalena' });
ciudades.push({ code: 418, name: 'Salamina - Magdalena' });
ciudades.push({ code: 419, name: 'San Zenón - Magdalena' });
ciudades.push({ code: 420, name: 'Santa Ana - Magdalena' });
ciudades.push({ code: 421, name: 'Sitionuevo - Magdalena' });
ciudades.push({ code: 422, name: 'Tenerife - Magdalena' });
ciudades.push({ code: 423, name: 'Zapayán - Magdalena' });
ciudades.push({ code: 424, name: 'Zona Bananera - Magdalena' });
ciudades.push({ code: 425, name: 'Villavicencio - Meta' });
ciudades.push({ code: 426, name: 'Acacias - Meta' });
ciudades.push({ code: 427, name: 'Cabuyaro - Meta' });
ciudades.push({ code: 428, name: 'Cubarral - Meta' });
ciudades.push({ code: 429, name: 'Cumaral - Meta' });
ciudades.push({ code: 430, name: 'El Calvario - Meta' });
ciudades.push({ code: 431, name: 'El Castillo - Meta' });
ciudades.push({ code: 432, name: 'El Dorado - Meta' });
ciudades.push({ code: 433, name: 'Granada - Meta' });
ciudades.push({ code: 434, name: 'Guamal - Meta' });
ciudades.push({ code: 435, name: 'Mapiripán - Meta' });
ciudades.push({ code: 436, name: 'Mesetas - Meta' });
ciudades.push({ code: 437, name: 'La Macarena - Meta' });
ciudades.push({ code: 438, name: 'Uribe - Meta' });
ciudades.push({ code: 439, name: 'Lejanías - Meta' });
ciudades.push({ code: 440, name: 'Puerto Concordia - Meta' });
ciudades.push({ code: 441, name: 'Puerto Gaitán - Meta' });
ciudades.push({ code: 442, name: 'Puerto López - Meta' });
ciudades.push({ code: 443, name: 'Puerto Lleras - Meta' });
ciudades.push({ code: 444, name: 'Puerto Rico - Meta' });
ciudades.push({ code: 445, name: 'Restrepo - Meta' });
ciudades.push({ code: 446, name: 'San Juanito - Meta' });
ciudades.push({ code: 447, name: 'San Martín - Meta' });
ciudades.push({ code: 448, name: 'Vista Hermosa - Meta' });
ciudades.push({ code: 449, name: 'Pasto - Nariño' });
ciudades.push({ code: 450, name: 'Albán - Nariño' });
ciudades.push({ code: 451, name: 'Aldana - Nariño' });
ciudades.push({ code: 452, name: 'Ancuyá - Nariño' });
ciudades.push({ code: 453, name: 'Barbacoas - Nariño' });
ciudades.push({ code: 454, name: 'Colón - Nariño' });
ciudades.push({ code: 455, name: 'Consaca - Nariño' });
ciudades.push({ code: 456, name: 'Contadero - Nariño' });
ciudades.push({ code: 457, name: 'Córdoba - Nariño' });
ciudades.push({ code: 458, name: 'Cuaspud - Nariño' });
ciudades.push({ code: 459, name: 'Cumbal - Nariño' });
ciudades.push({ code: 460, name: 'Cumbitara - Nariño' });
ciudades.push({ code: 461, name: 'El Charco - Nariño' });
ciudades.push({ code: 462, name: 'El Peñol - Nariño' });
ciudades.push({ code: 463, name: 'El Rosario - Nariño' });
ciudades.push({ code: 464, name: 'El Tambo - Nariño' });
ciudades.push({ code: 465, name: 'Funes - Nariño' });
ciudades.push({ code: 466, name: 'Guachucal - Nariño' });
ciudades.push({ code: 467, name: 'Guaitarilla - Nariño' });
ciudades.push({ code: 468, name: 'Gualmatán - Nariño' });
ciudades.push({ code: 469, name: 'Iles - Nariño' });
ciudades.push({ code: 470, name: 'Imués - Nariño' });
ciudades.push({ code: 471, name: 'Ipiales - Nariño' });
ciudades.push({ code: 472, name: 'La Cruz - Nariño' });
ciudades.push({ code: 473, name: 'La Florida - Nariño' });
ciudades.push({ code: 474, name: 'La Llanada - Nariño' });
ciudades.push({ code: 475, name: 'La Tola - Nariño' });
ciudades.push({ code: 476, name: 'La Unión - Nariño' });
ciudades.push({ code: 477, name: 'Leiva - Nariño' });
ciudades.push({ code: 478, name: 'Linares - Nariño' });
ciudades.push({ code: 479, name: 'Los Andes - Nariño' });
ciudades.push({ code: 480, name: 'Magüí - Nariño' });
ciudades.push({ code: 481, name: 'Mallama - Nariño' });
ciudades.push({ code: 482, name: 'Mosquera - Nariño' });
ciudades.push({ code: 483, name: 'Nariño - Nariño' });
ciudades.push({ code: 484, name: 'Olaya Herrera - Nariño' });
ciudades.push({ code: 485, name: 'Ospina - Nariño' });
ciudades.push({ code: 486, name: 'Francisco Pizarro - Nariño' });
ciudades.push({ code: 487, name: 'Policarpa - Nariño' });
ciudades.push({ code: 488, name: 'Potosí - Nariño' });
ciudades.push({ code: 489, name: 'Providencia - Nariño' });
ciudades.push({ code: 490, name: 'Puerres - Nariño' });
ciudades.push({ code: 491, name: 'Pupiales - Nariño' });
ciudades.push({ code: 492, name: 'Ricaurte - Nariño' });
ciudades.push({ code: 493, name: 'Roberto Payán - Nariño' });
ciudades.push({ code: 494, name: 'Samaniego - Nariño' });
ciudades.push({ code: 495, name: 'Sandoná - Nariño' });
ciudades.push({ code: 496, name: 'San Bernardo - Nariño' });
ciudades.push({ code: 497, name: 'San Lorenzo - Nariño' });
ciudades.push({ code: 498, name: 'San Pablo - Nariño' });
ciudades.push({ code: 499, name: 'Santa Bárbara - Nariño' });
ciudades.push({ code: 500, name: 'Sapuyes - Nariño' });
ciudades.push({ code: 501, name: 'Taminango - Nariño' });
ciudades.push({ code: 502, name: 'Tangua - Nariño' });
ciudades.push({ code: 503, name: 'Túquerres - Nariño' });
ciudades.push({ code: 504, name: 'Yacuanquer - Nariño' });
ciudades.push({ code: 505, name: 'Armenia - Quindio' });
ciudades.push({ code: 506, name: 'Buenavista - Quindio' });
ciudades.push({ code: 507, name: 'Circasia - Quindio' });
ciudades.push({ code: 508, name: 'Córdoba - Quindio' });
ciudades.push({ code: 509, name: 'Filandia - Quindio' });
ciudades.push({ code: 510, name: 'La Tebaida - Quindio' });
ciudades.push({ code: 511, name: 'Montenegro - Quindio' });
ciudades.push({ code: 512, name: 'Pijao - Quindio' });
ciudades.push({ code: 513, name: 'Quimbaya - Quindio' });
ciudades.push({ code: 514, name: 'Salento - Quindio' });
ciudades.push({ code: 515, name: 'Pereira - Risaralda' });
ciudades.push({ code: 516, name: 'Apía - Risaralda' });
ciudades.push({ code: 517, name: 'Balboa - Risaralda' });
ciudades.push({ code: 518, name: 'Dosquebradas - Risaralda' });
ciudades.push({ code: 519, name: 'Guática - Risaralda' });
ciudades.push({ code: 520, name: 'La Celia - Risaralda' });
ciudades.push({ code: 521, name: 'La Virginia - Risaralda' });
ciudades.push({ code: 522, name: 'Marsella - Risaralda' });
ciudades.push({ code: 523, name: 'Mistrató - Risaralda' });
ciudades.push({ code: 524, name: 'Pueblo Rico - Risaralda' });
ciudades.push({ code: 525, name: 'Quinchía - Risaralda' });
ciudades.push({ code: 526, name: 'Santuario - Risaralda' });
ciudades.push({ code: 527, name: 'Bucaramanga - Santander' });
ciudades.push({ code: 528, name: 'Aguada - Santander' });
ciudades.push({ code: 529, name: 'Albania - Santander' });
ciudades.push({ code: 530, name: 'Aratoca - Santander' });
ciudades.push({ code: 531, name: 'Barbosa - Santander' });
ciudades.push({ code: 532, name: 'Barichara - Santander' });
ciudades.push({ code: 533, name: 'Barrancabermeja - Santander' });
ciudades.push({ code: 534, name: 'Betulia - Santander' });
ciudades.push({ code: 535, name: 'Bolívar - Santander' });
ciudades.push({ code: 536, name: 'Cabrera - Santander' });
ciudades.push({ code: 537, name: 'California - Santander' });
ciudades.push({ code: 538, name: 'Carcasí - Santander' });
ciudades.push({ code: 539, name: 'Cepitá - Santander' });
ciudades.push({ code: 540, name: 'Cerrito - Santander' });
ciudades.push({ code: 541, name: 'Charalá - Santander' });
ciudades.push({ code: 542, name: 'Charta - Santander' });
ciudades.push({ code: 543, name: 'Chipatá - Santander' });
ciudades.push({ code: 544, name: 'Cimitarra - Santander' });
ciudades.push({ code: 545, name: 'Concepción - Santander' });
ciudades.push({ code: 546, name: 'Confines - Santander' });
ciudades.push({ code: 547, name: 'Contratación - Santander' });
ciudades.push({ code: 548, name: 'Coromoro - Santander' });
ciudades.push({ code: 549, name: 'Curití - Santander' });
ciudades.push({ code: 550, name: 'El Guacamayo - Santander' });
ciudades.push({ code: 551, name: 'El Playón - Santander' });
ciudades.push({ code: 552, name: 'Encino - Santander' });
ciudades.push({ code: 553, name: 'Enciso - Santander' });
ciudades.push({ code: 554, name: 'Florián - Santander' });
ciudades.push({ code: 555, name: 'Floridablanca - Santander' });
ciudades.push({ code: 556, name: 'Galán - Santander' });
ciudades.push({ code: 557, name: 'Gambita - Santander' });
ciudades.push({ code: 558, name: 'Girón - Santander' });
ciudades.push({ code: 559, name: 'Guaca - Santander' });
ciudades.push({ code: 560, name: 'Guadalupe - Santander' });
ciudades.push({ code: 561, name: 'Guapotá - Santander' });
ciudades.push({ code: 562, name: 'Guavatá - Santander' });
ciudades.push({ code: 563, name: 'Güepsa - Santander' });
ciudades.push({ code: 564, name: 'Jesús María - Santander' });
ciudades.push({ code: 565, name: 'Jordán - Santander' });
ciudades.push({ code: 566, name: 'La Belleza - Santander' });
ciudades.push({ code: 567, name: 'Landázuri - Santander' });
ciudades.push({ code: 568, name: 'La Paz - Santander' });
ciudades.push({ code: 569, name: 'Lebríja - Santander' });
ciudades.push({ code: 570, name: 'Los Santos - Santander' });
ciudades.push({ code: 571, name: 'Macaravita - Santander' });
ciudades.push({ code: 572, name: 'Málaga - Santander' });
ciudades.push({ code: 573, name: 'Matanza - Santander' });
ciudades.push({ code: 574, name: 'Mogotes - Santander' });
ciudades.push({ code: 575, name: 'Molagavita - Santander' });
ciudades.push({ code: 576, name: 'Ocamonte - Santander' });
ciudades.push({ code: 577, name: 'Oiba - Santander' });
ciudades.push({ code: 578, name: 'Onzaga - Santander' });
ciudades.push({ code: 579, name: 'Palmar - Santander' });
ciudades.push({ code: 580, name: 'Páramo - Santander' });
ciudades.push({ code: 581, name: 'Piedecuesta - Santander' });
ciudades.push({ code: 582, name: 'Pinchote - Santander' });
ciudades.push({ code: 583, name: 'Puente Nacional - Santander' });
ciudades.push({ code: 584, name: 'Rionegro - Santander' });
ciudades.push({ code: 585, name: 'San Andrés - Santander' });
ciudades.push({ code: 586, name: 'San Gil - Santander' });
ciudades.push({ code: 587, name: 'San Joaquín - Santander' });
ciudades.push({ code: 588, name: 'San Miguel - Santander' });
ciudades.push({ code: 589, name: 'Santa Bárbara - Santander' });
ciudades.push({ code: 590, name: 'Simacota - Santander' });
ciudades.push({ code: 591, name: 'Socorro - Santander' });
ciudades.push({ code: 592, name: 'Suaita - Santander' });
ciudades.push({ code: 593, name: 'Sucre - Santander' });
ciudades.push({ code: 594, name: 'Suratá - Santander' });
ciudades.push({ code: 595, name: 'Tona - Santander' });
ciudades.push({ code: 596, name: 'Vélez - Santander' });
ciudades.push({ code: 597, name: 'Vetas - Santander' });
ciudades.push({ code: 598, name: 'Villanueva - Santander' });
ciudades.push({ code: 599, name: 'Zapatoca - Santander' });
ciudades.push({ code: 600, name: 'Sincelejo - Sucre' });
ciudades.push({ code: 601, name: 'Buenavista - Sucre' });
ciudades.push({ code: 602, name: 'Caimito - Sucre' });
ciudades.push({ code: 603, name: 'Coloso - Sucre' });
ciudades.push({ code: 604, name: 'Coveñas - Sucre' });
ciudades.push({ code: 605, name: 'Chalán - Sucre' });
ciudades.push({ code: 606, name: 'El Roble - Sucre' });
ciudades.push({ code: 607, name: 'Galeras - Sucre' });
ciudades.push({ code: 608, name: 'Guaranda - Sucre' });
ciudades.push({ code: 609, name: 'La Unión - Sucre' });
ciudades.push({ code: 610, name: 'Los Palmitos - Sucre' });
ciudades.push({ code: 611, name: 'Majagual - Sucre' });
ciudades.push({ code: 612, name: 'Morroa - Sucre' });
ciudades.push({ code: 613, name: 'Ovejas - Sucre' });
ciudades.push({ code: 614, name: 'Palmito - Sucre' });
ciudades.push({ code: 615, name: 'San Benito Abad - Sucre' });
ciudades.push({ code: 616, name: 'San Marcos - Sucre' });
ciudades.push({ code: 617, name: 'San Onofre - Sucre' });
ciudades.push({ code: 618, name: 'San Pedro - Sucre' });
ciudades.push({ code: 619, name: 'Sucre - Sucre' });
ciudades.push({ code: 620, name: 'Tolú Viejo - Sucre' });
ciudades.push({ code: 621, name: 'Alpujarra - Tolima' });
ciudades.push({ code: 622, name: 'Alvarado - Tolima' });
ciudades.push({ code: 623, name: 'Ambalema - Tolima' });
ciudades.push({ code: 624, name: 'Armero - Tolima' });
ciudades.push({ code: 625, name: 'Ataco - Tolima' });
ciudades.push({ code: 626, name: 'Cajamarca - Tolima' });
ciudades.push({ code: 627, name: 'Chaparral - Tolima' });
ciudades.push({ code: 628, name: 'Coello - Tolima' });
ciudades.push({ code: 629, name: 'Coyaima - Tolima' });
ciudades.push({ code: 630, name: 'Cunday - Tolima' });
ciudades.push({ code: 631, name: 'Dolores - Tolima' });
ciudades.push({ code: 632, name: 'Espinal - Tolima' });
ciudades.push({ code: 633, name: 'Falan - Tolima' });
ciudades.push({ code: 634, name: 'Flandes - Tolima' });
ciudades.push({ code: 635, name: 'Fresno - Tolima' });
ciudades.push({ code: 636, name: 'Guamo - Tolima' });
ciudades.push({ code: 637, name: 'Herveo - Tolima' });
ciudades.push({ code: 638, name: 'Honda - Tolima' });
ciudades.push({ code: 639, name: 'Icononzo - Tolima' });
ciudades.push({ code: 640, name: 'Mariquita - Tolima' });
ciudades.push({ code: 641, name: 'Melgar - Tolima' });
ciudades.push({ code: 642, name: 'Murillo - Tolima' });
ciudades.push({ code: 643, name: 'Natagaima - Tolima' });
ciudades.push({ code: 644, name: 'Ortega - Tolima' });
ciudades.push({ code: 645, name: 'Palocabildo - Tolima' });
ciudades.push({ code: 646, name: 'Piedras - Tolima' });
ciudades.push({ code: 647, name: 'Planadas - Tolima' });
ciudades.push({ code: 648, name: 'Prado - Tolima' });
ciudades.push({ code: 649, name: 'Purificación - Tolima' });
ciudades.push({ code: 650, name: 'Rio Blanco - Tolima' });
ciudades.push({ code: 651, name: 'Roncesvalles - Tolima' });
ciudades.push({ code: 652, name: 'Rovira - Tolima' });
ciudades.push({ code: 653, name: 'Saldaña - Tolima' });
ciudades.push({ code: 654, name: 'Santa Isabel - Tolima' });
ciudades.push({ code: 655, name: 'Venadillo - Tolima' });
ciudades.push({ code: 656, name: 'Villahermosa - Tolima' });
ciudades.push({ code: 657, name: 'Villarrica - Tolima' });
ciudades.push({ code: 658, name: 'Arauquita - Arauca' });
ciudades.push({ code: 659, name: 'Cravo Norte - Arauca' });
ciudades.push({ code: 660, name: 'Fortul - Arauca' });
ciudades.push({ code: 661, name: 'Puerto Rondón - Arauca' });
ciudades.push({ code: 662, name: 'Saravena - Arauca' });
ciudades.push({ code: 663, name: 'Tame - Arauca' });
ciudades.push({ code: 664, name: 'Arauca - Arauca' });
ciudades.push({ code: 665, name: 'Yopal - Casanare' });
ciudades.push({ code: 666, name: 'Aguazul - Casanare' });
ciudades.push({ code: 667, name: 'Chámeza - Casanare' });
ciudades.push({ code: 668, name: 'Hato Corozal - Casanare' });
ciudades.push({ code: 669, name: 'La Salina - Casanare' });
ciudades.push({ code: 670, name: 'Monterrey - Casanare' });
ciudades.push({ code: 671, name: 'Pore - Casanare' });
ciudades.push({ code: 672, name: 'Recetor - Casanare' });
ciudades.push({ code: 673, name: 'Sabanalarga - Casanare' });
ciudades.push({ code: 674, name: 'Sácama - Casanare' });
ciudades.push({ code: 675, name: 'Tauramena - Casanare' });
ciudades.push({ code: 676, name: 'Trinidad - Casanare' });
ciudades.push({ code: 677, name: 'Villanueva - Casanare' });
ciudades.push({ code: 678, name: 'Mocoa - Putumayo' });
ciudades.push({ code: 679, name: 'Colón - Putumayo' });
ciudades.push({ code: 680, name: 'Orito - Putumayo' });
ciudades.push({ code: 681, name: 'Puerto Caicedo - Putumayo' });
ciudades.push({ code: 682, name: 'Puerto Guzmán - Putumayo' });
ciudades.push({ code: 683, name: 'Leguízamo - Putumayo' });
ciudades.push({ code: 684, name: 'Sibundoy - Putumayo' });
ciudades.push({ code: 685, name: 'San Francisco - Putumayo' });
ciudades.push({ code: 686, name: 'San Miguel - Putumayo' });
ciudades.push({ code: 687, name: 'Santiago - Putumayo' });
ciudades.push({ code: 688, name: 'Leticia - Amazonas' });
ciudades.push({ code: 689, name: 'El Encanto - Amazonas' });
ciudades.push({ code: 690, name: 'La Chorrera - Amazonas' });
ciudades.push({ code: 691, name: 'La Pedrera - Amazonas' });
ciudades.push({ code: 692, name: 'La Victoria - Amazonas' });
ciudades.push({ code: 693, name: 'Puerto Arica - Amazonas' });
ciudades.push({ code: 694, name: 'Puerto Nariño - Amazonas' });
ciudades.push({ code: 695, name: 'Puerto Santander - Amazonas' });
ciudades.push({ code: 696, name: 'Tarapacá - Amazonas' });
ciudades.push({ code: 697, name: 'Inírida - Guainía' });
ciudades.push({ code: 698, name: 'Barranco Minas - Guainía' });
ciudades.push({ code: 699, name: 'Mapiripana - Guainía' });
ciudades.push({ code: 700, name: 'San Felipe - Guainía' });
ciudades.push({ code: 701, name: 'Puerto Colombia - Guainía' });
ciudades.push({ code: 702, name: 'La Guadalupe - Guainía' });
ciudades.push({ code: 703, name: 'Cacahual - Guainía' });
ciudades.push({ code: 704, name: 'Pana Pana - Guainía' });
ciudades.push({ code: 705, name: 'Morichal - Guainía' });
ciudades.push({ code: 706, name: 'Mitú - Vaupés' });
ciudades.push({ code: 707, name: 'Caruru - Vaupés' });
ciudades.push({ code: 708, name: 'Pacoa - Vaupés' });
ciudades.push({ code: 709, name: 'Taraira - Vaupés' });
ciudades.push({ code: 710, name: 'Papunaua - Vaupés' });
ciudades.push({ code: 711, name: 'Puerto Carreño - Vichada' });
ciudades.push({ code: 712, name: 'La Primavera - Vichada' });
ciudades.push({ code: 713, name: 'Santa Rosalía - Vichada' });
ciudades.push({ code: 714, name: 'Cumaribo - Vichada' });
ciudades.push({ code: 715, name: 'San José del Fragua - Caqueta' });
ciudades.push({ code: 716, name: 'Barranca de Upía - Meta' });
ciudades.push({ code: 717, name: 'Palmas del Socorro - Satander' });
ciudades.push({ code: 718, name: 'San Juan de Río Seco - Cundinamarca' });
ciudades.push({ code: 719, name: 'Juan de Acosta - Atlantico' });
ciudades.push({ code: 720, name: 'Fuente de Oro - Meta' });
ciudades.push({ code: 721, name: 'San Luis de Gaceno - Casanare' });
ciudades.push({ code: 722, name: 'El Litoral del San Juan - Chocó' });
ciudades.push({ code: 723, name: 'Villa de San Diego de Ubate - Cundinamarca' });
ciudades.push({ code: 724, name: 'Barranco de Loba - Bolivar' });
ciudades.push({ code: 725, name: 'Togüí - Boyaca' });
ciudades.push({ code: 726, name: 'Santa Rosa del Sur - Bolivar' });
ciudades.push({ code: 727, name: 'El Cantón del San Pablo - Chocó' });
ciudades.push({ code: 728, name: 'Villa de Leyva - Boyaca' });
ciudades.push({ code: 729, name: 'San Sebastián de Buenavista - Magdalena' });
ciudades.push({ code: 730, name: 'Paz de Río - Boyaca' });
ciudades.push({ code: 731, name: 'Hatillo de Loba - Bolivar' });
ciudades.push({ code: 732, name: 'Sabanas de San Angel - Magdalena' });
ciudades.push({ code: 733, name: 'Calamar - Guaviare' });
ciudades.push({ code: 734, name: 'Río de Oro - Cesar' });
ciudades.push({ code: 735, name: 'San Pedro de Uraba - Antioquia' });
ciudades.push({ code: 736, name: 'San José del Guaviare - Guaviare' });
ciudades.push({ code: 737, name: 'Santa Rosa de Viterbo - Boyaca' });
ciudades.push({ code: 738, name: 'Santander de Quilichao - Cauca' });